---
name: comment-test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2.6.2
        with:
          message: |
            ${{ github.sha }}
