---
name: pr-synchronize
run-name: pr synchronize
on:
  pull_request:
    types:
      - synchronize
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$DATA"
        env:
          DATA: ${{ toJson(github) }}
      - run: echo "$DATA"
        env:
          DATA: ${{ toJson(inputs) }}
